### ISSUE TITLE
QcodeEditor needed for QML devices

### ISSUE THREAD

**Issue by thibaudk** [ossia/sdk#1]
How may I include it in the sdk ?

**Comment by jcelerier** [comment]
huh ? it's part of score

**Comment by thibaudk** [comment]
For compiling external addons.
curently i get this error in the CMake build that i don't have on my machine
https://github.com/thibaudk/score-addon-stdIO/runs/3321235607?check_suite_focus=true#step:6:98

**Comment by jcelerier** [comment]
ah ! okay, it means that the headers needs to be installed.
The simplest is to add them to the list here: 

https://github.com/ossia/score/blob/master/src/lib/CMakeLists.txt#L22
